### ISSUE TITLE
Not working with Seamless Co-op & Randomizer

### ISSUE THREAD

**Issue by RamenFiend** [Cloudef/ModEngine2#1]
X-Post from https://github.com/soulsmods/ModEngine2/issues/58
Including previously posted info:

Hello @Cloudef , I've used your guide & build to attempt installing Randomizer + Seamless Co-Op under Arch w/ Proton Experimental. However, it results in a very similar issue to that described here. Seamless co-op launches fine, however Randomizer appears to not work (judging based on character creation screen) and the game will crash when attempting new character creation or loading a previous save. For the record, I've renamed elden_ring_seamless_coop.dll to seamless_coop.dll and I have the same content as the release notes in my modengine.toml. I have also tried Proton-GE and Proton 7 with the same results. Steam launch command is the same as described in release notes. Randomizer .exe was run with system wine and the application seemed to work fine. I also tried copying the randomizer directory from a Windows VM with no luck. I'll be attaching my logs (although everything seems to be working correctly by looking at them?) and my configs and directory structure. Thanks!
[mod_loader_log.txt](https://github.com/soulsmods/ModEngine2/files/8985853/mod_loader_log.txt)
[modengine_2022-06-25.log](https://github.com/soulsmods/ModEngine2/files/8985854/modengine_2022-06-25.log)
[find.txt](https://github.com/soulsmods/ModEngine2/files/8985860/find.txt)
[config_eldenringrandomizer.toml.txt](https://github.com/soulsmods/ModEngine2/files/8985991/config_eldenringrandomizer.toml.txt)
[mod_loader_config.ini.txt](https://github.com/soulsmods/ModEngine2/files/8985987/mod_loader_config.ini.txt)
[modengine.toml.txt](https://github.com/soulsmods/ModEngine2/files/8985986/modengine.toml.txt)
(.txt extensions added so GH will let me upload them)
P.S. there is a slight typo in the release notes, modengine.toml is referenced as modengine2.toml under the "How to use with enemy / item randomizer?" heading.

Still not working with proton-v3 release. No longer crashes after character creation/load, but randomizer still isn't working. I would've x-posted this as an issue to your fork but I don't think issues are enabled on it. 
```
md5sum modengine2.dll
15883ee3c55f1da1858f1677e7933508  modengine2.dll

md5sum eldenring.exe
36d03670099eb4037c5a9546db6cd7a7  eldenring.exe
```
It appears the US locale .exe is different from yours. For the record, the old (v2) modengine.2 dll:
```
md5sum modengine2.dll
2c65db279c481d62da31a329466a84ed  modengine2.dll
```

**Comment by Cloudef** [comment]
Your file layout looks correct. Can I have latest `modengine_<date>.log` file with the -v3?

**Comment by RamenFiend** [comment]
Attaching a new modengine.log for v3:
[modengine_2022-06-26.log](https://github.com/Cloudef/ModEngine2/files/8986710/modengine_2022-06-26.log)
It appears all 3 dlls are getting hooked correctly.

Screenshots of file layout:
![Screenshot_20220626_083019](https://user-images.githubusercontent.com/97411685/175816530-31f2e13b-985a-4cae-9e2a-8701d393a5b0.png)
![Screenshot_20220626_083028](https://user-images.githubusercontent.com/97411685/175816533-92e29990-516b-4701-9b34-7360bf1adda2.png)
![Screenshot_20220626_083037](https://user-images.githubusercontent.com/97411685/175816534-24ebfbea-33c7-43f4-b542-2a0bd5bb710c.png)
![Screenshot_20220626_083043](https://user-images.githubusercontent.com/97411685/175816535-2453e3a4-5498-424d-880e-4db0eb35e84d.png)

**Comment by Cloudef** [comment]
>[2022-06-26 08:12:46.182] [modengine] [warning] Unable to resolve mod path

This is most likely the problem

Though it seems your earlier launches were okay:

>[2022-06-26 08:10:44.135] [modengine] [info] Resolved mod path to Z:\home\quinn\.local\share\Steam\steamapps\common\ELDEN RING\Game\randomizer

The randomizer should be loaded in this case.

**Comment by RamenFiend** [comment]
[modengine_2022-06-26.log](https://github.com/Cloudef/ModEngine2/files/8986720/modengine_2022-06-26.log)
Sorry, last unable to resolve was a result of me attempting some debugging. Check last run in this log.

**Comment by Cloudef** [comment]
Okay, that looks like everything is fine. What randomizer settings did you use? Can you post the randomizer window.

**Comment by RamenFiend** [comment]
Basically default settings. Randomizer exe run with system wine. Starting classes, etc unrandomized in-game.
![Screenshot_20220626_083647](https://user-images.githubusercontent.com/97411685/175817001-1f87dc62-f2f3-41eb-85b0-a8cee7aef17d.png)
![Screenshot_20220626_083955](https://user-images.githubusercontent.com/97411685/175817002-48a4a326-de22-49d4-8606-eec8a39c14a9.png)
![Screenshot_20220626_084000](https://user-images.githubusercontent.com/97411685/175817003-d1e83e5a-eb79-4ee1-a862-d078a0edda14.png)

**Comment by Cloudef** [comment]
Ok everything seems fine, not sure why it does not work. The logic should be same to the vanilla modengine regarding to memory scanning. Does other mods work?

**Comment by Cloudef** [comment]
Also can you check if it's only items that don't get randomized. If enemies get randomized, it might be related to the hardcoded address used for all souls games. (Item randomization works with that)

**Comment by RamenFiend** [comment]
Okay, yeah. Enemy randomization is working. Grafted Scion was replaced with a troll. The text strings associated with prompts and boss health appear to be broken too, reading ?MapText? and ?NpcName?. Just downloaded Reforged to see if it works fine.

**Comment by RamenFiend** [comment]
Reforged works I think? I'm not sure what it changes, although the starting classes and Grafted Scion appear the same. It did break the HUD UI though, with nothing appearing.

**Comment by Cloudef** [comment]
Okay, it might be related to this https://github.com/Cloudef/ModEngine2/blob/feat/overlay-scripting/src/modengine/ext/mod_loader/mod_loader_extension.cpp#L56 which is funny because normal modloader2 has this too. I can check if I can scan this address too later.

**Comment by RamenFiend** [comment]
Yeah, checked the reforged change notes and the starting talismans aren't present, along with the mod's UI issues. Seems to be the same issue as is affecting randomizer.

**Comment by Cloudef** [comment]
@Lejaxak what proton are you use btw?

**Comment by RamenFiend** [comment]
Proton Experimental, although I've tried 7 and latest GE.

**Comment by Cloudef** [comment]
Ok, I'm using GE. Not sure what's the problem. Is your proton prefix clean? Anything else custom in your setup? Maybe try playing with the `load_delay` in `mod_loader_config.ini`. Perhaps elden ring loads some of the stuff before the hooks kick in.

**Comment by RamenFiend** [comment]
Last install I did was deleting the ER install directory and prefix, then doing a clean install following the provided instructions with no other mods included. I ended up doing an unarchived install of randomizer with UXM and launching through the seamless co-op launcher, which works just fine. I'll play around with the load delay later, and see if that changes anything. Thank you so much for the help with this.

**Comment by RamenFiend** [comment]
Okay, had some time to experiment with it and this issue is resolved. Decreasing EML load delay to 2500 (down from 5000 default) resolves all the issues. Seems ER was loading before EML could hook the game correctly, like you guessed. For reference I use 2 NVMe drives in RAID for my system, so it may be dependent on I/O throughput. Thank you again for all your help and this excellent modengine fork.
