### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Pednick** [Cloudef/ModEngine2#10]
How do you include mangohud in these launch options?

echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" sh

**Comment by Cloudef** [comment]
That depends how you have mangohud setup. Usually you don't have to put it in launch options at all, but you can use the  MANGOHUD env variable to 1 if you absolutely want it in the launch options, then:
`echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" MANGOHUD=1 sh`

**Comment by Pednick** [comment]
> That depends how you have mangohud setup. Usually you don't have to put it in launch options at all, but you can use the MANGOHUD env variable to 1 if you absolutely want it in the launch options, then: `echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" MANGOHUD=1 sh`

Wow quick response, thank you so much.

**Comment by Pednick** [comment]
Thank you very much.
