### ISSUE TITLE
modengine: Unable to detect a supported game

### ISSUE THREAD

**Issue by DiabeticCrab** [Cloudef/ModEngine2#11]
I tried to use this with the "Grand Merchant" mod under Linux and I've set up mod loader as described on the "releases" page. Modloader does in fact load lua.dll, aswell as modengine2.dll, but somehow me2 doesn't recognize the game (ER version 1.08.1).

modengine_YYYY-MM-DD.log:
[2023-01-24 22:11:10.875] **[modengine] [error] Unable to detect a supported game**

[mod_loader_config.ini.txt](https://github.com/Cloudef/ModEngine2/files/10494093/mod_loader_config.ini.txt)
[modengine.toml.txt](https://github.com/Cloudef/ModEngine2/files/10494094/modengine.toml.txt)
[mod_loader_log.txt](https://github.com/Cloudef/ModEngine2/files/10494096/mod_loader_log.txt)
[modengine_2023-01-24.log](https://github.com/Cloudef/ModEngine2/files/10494097/modengine_2023-01-24.log)

My Elden Ring game folder:
```
├── amd_ags_x64.dll
├── bink2w64.dll
├── Data0.bdt
├── Data0.bhd
├── Data1.bdt
├── Data1.bhd
├── Data2.bdt
├── Data2.bhd
├── Data3.bdt
├── Data3.bhd
├── dinput8.dll
├── EasyAntiCheat
│   ├── Certificates
│   │   ├── base.bin
│   │   └── base.cer
│   ├── easyanticheat_eos_setup.exe
│   ├── install_easyanticheat_eos_setup.bat
│   ├── install_script.vdf
│   ├── licenses
│   │   ├── *
│   ├── localization
│   │   ├── *
│   ├── settings.json
│   ├── splashscreen.png
│   └── uninstall_easyanticheat_eos_setup.bat
├── eldenring.exe
├── eossdk-win64-shipping.dll
├── eossdk-win64-shipping.so
├── merchant
│   ├── msg
│   │   └── engus
│   │       └── menu.msgbnd.dcx
│   ├── regulation.bin
│   └── script
│       └── talk
│           ├── esdtoolconfig.json
│           ├── m11_00_00_00.talkesdbnd.dcx
│           ├── m11_00_00_00.talkesdbnd.dcx.bak
│           ├── m35_00_00_00.talkesdbnd.dcx
│           ├── m35_00_00_00.talkesdbnd.dcx.bak
│           ├── m60_00_00_00.talkesdbnd.dcx
│           ├── m60_00_00_00.talkesdbnd.dcx.bak
│           └── output  [173 entries exceeds filelimit, not opening dir]
├── modengine_2023-01-24.log
├── modengine.toml
├── mod_loader_config.ini
├── mod_loader_log.txt
├── mods
│   ├── lua.dll
│   └── modengine2.dll
├── movie
│   ├── *
├── oo2core_6_win64.dll
├── regulation.bin
├── sd
│   ├── sd.bdt
│   └── sd.bhd
├── start_protected_game.exe
├── start_protected_game.exe.orig
├── steam_api64.dll
├── vkd3d-proton.cache
└── vkd3d-proton.cache.write
```
Steam game launch options:
`gamemoderun env WINEDLLOVERRIDES="dinput8.dll=n,b" PROTON_NO_ESYNC=1 MANGOHUD=1 VKD3D_FEATURE_LEVEL=12_0 %command%`

I also tried to launch the game via a Proton CMD by using it to run launchmod_eldenring.bat,
which in turn tries to open the game via modengine2_launcher.exe. In that case the game doesn't even open because the launcher "can't find any game files", despite being right next to eldenring.exe…

Do you have an idea what else I could try, or is it that ME2 itself needs an update? Any help is greatly appreciated. TYVM.

**Comment by Cloudef** [comment]
Try this 
`echo "gamemoderun %command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" PROTON_NO_ESYNC=1 MANGOHUD=1 VKD3D_FEATURE_LEVEL=12_0 sh`
If it does not work, then the latest patch no longer works with this fork
