### ISSUE TITLE
Another quick question

### ISSUE THREAD

**Issue by Pednick** [Cloudef/ModEngine2#13]
How do you include DXVK_HUD=full in these launch options?

echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" sh

**Comment by Cloudef** [comment]
`echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" DXVK_HUD=full sh`

**Comment by Pednick** [comment]
> `echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" DXVK_HUD=full sh`

Already tried that, it doesn't work. I too thought that should work.

**Comment by Cloudef** [comment]
It does work, but the real reason you don't see anything is because Elden Ring uses D3D12 which doesn't use DXVK, but vkd3d-proton https://github.com/HansKristian-Work/vkd3d-proton

Consider mangohud if you want general FPS / perf overlay https://github.com/flightlessmango/MangoHud

**Comment by Pednick** [comment]
> It does work, but the real reason you don't see anything is because Elden Ring uses D3D12 which doesn't use DXVK, but vkd3d-proton https://github.com/HansKristian-Work/vkd3d-proton
> 
> Consider mangohud if you want general FPS / perf overlay https://github.com/flightlessmango/MangoHud

I thought steam proton has vkd3d-proton already installed.
I already have MangoHud, that works fine, just wanted to see how vkd3d-proton
performs. It's alright, doesn't matter.

**Comment by Cloudef** [comment]
dxvk and vkd3d-proton are different things, DXVK_HUD only works with dxvk (dx9 and dx11 games, elden ring uses dx12).

**Comment by Pednick** [comment]
> dxvk and vkd3d-proton are different things, DXVK_HUD only works with dxvk (dx9 and dx11 games, elden ring uses dx12).

Yes, I know what each does, I installed vkd3d-proton on my wine, never mind about elen ring, I'm going to download a d3d12 game and see how that goes, thanks for your response, I will be closing this now.
