### ISSUE TITLE
wine command prompt

### ISSUE THREAD

**Issue by Pednick** [Cloudef/ModEngine2#17]
How  would I type this command:
echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" sh

Using wine on the command prompt.

**Comment by Cloudef** [comment]
`WINEDLLOVERRIDES="dinput8.dll=n,b" wine eldenring.exe`

**Comment by Pednick** [comment]
> `WINEDLLOVERRIDES="dinput8.dll=n,b" wine eldenring.exe`

Thank you.
