### ISSUE TITLE
Armored Core 6 support

### ISSUE THREAD

**Issue by sevenpastzeero** [Cloudef/ModEngine2#19]
Can this be updated to support Armored Core 6?

**Comment by Cloudef** [comment]
I rebased against upstream and build came out fine. I don't have AC6 to test so can you test this for me before I make release? Also you will need something like elden mod loader to inject the DLL itself.
[ModEngine-2.1.0.0-win64.zip](https://github.com/Cloudef/ModEngine2/files/12554678/ModEngine-2.1.0.0-win64.zip)

**Comment by sevenpastzeero** [comment]
It worked with mods that use 'regualtion.bin' like these two: https://www.nexusmods.com/armoredcore6firesofrubicon/mods/25
https://www.nexusmods.com/armoredcore6firesofrubicon/mods/48?tab=files&file_id=98

But did not work with mod like these: https://www.nexusmods.com/armoredcore6firesofrubicon/mods/26
https://www.nexusmods.com/armoredcore6firesofrubicon/mods/35

Just like the original ModEngine2.
I think it has something to do with files paths. I've been trying for two days.
I opened a ticket in the original modengine2 page stating these issues.

For the dll inject I found this Lazy Loader working with Armored Core 6: https://modslab.net/en/armored_core_vi_fires_of_rubicon/mods/ReAaefZ9fY/

My setup was correct, another dll to skip title worked.

Also I am familiar with your for foe elden ring + elden ring loader. I used it before to mod elden ring's text size on the Deck and it worked. So my guess it is something to do with modengine2 itself.

**Comment by Cloudef** [comment]
I noticed I made typo in my rebase. I'll give you new zip.

**Comment by Cloudef** [comment]
How's this?
[ModEngine-2.1.0.0-win64.zip](https://github.com/Cloudef/ModEngine2/files/12564361/ModEngine-2.1.0.0-win64.zip)

**Comment by sevenpastzeero** [comment]
This worked!! Finally! I was about to give up.
Thank you very much.
My test setup was like this:
Path to installed Steam games `/home/deck/.steam/steam/steamapps/common`

```
ARMORED CORE VI FIRES OF RUBICON
└── Game
    ├── dllMods
    │       ├── lua.dll
    │       └── modengine2.dll
    ├── mod
    │       ├── font			    (Text size increase mod)
    │       ├── parts			    (Thomas The Tank Engine Wheelchair Swap mod)
    │       ├── msg			    (Poorly Translated AC6 mod)
    │       └── regulation.bin         (Generator Colors mod)
    ├── armoredcore6.exe and all other original game files here
    ├── dinput8.dll
    ├── lazyLoad.ini
    └── modengine.toml		    (config_armoredcore6.toml renamed)
```

Lazy Loader downloaded from here: https://modslab.net/en/armored_core_vi_fires_of_rubicon/mods/ReAaefZ9fY/

A couple of screenshots:
![Screenshot 2023-09-09 212939](https://github.com/Cloudef/ModEngine2/assets/34801304/0724bfb5-c9c8-4876-b7a4-17de0f488502)
![Screenshot 2023-09-09 213049](https://github.com/Cloudef/ModEngine2/assets/34801304/b78b1793-eab8-449b-890a-4f9244502290)

Thank you very much. Now my eyes can read the in game text again lol.

**Comment by sevenpastzeero** [comment]
I should add that I added this `WINEDLLOVERRIDES="dinput8.dll=n,b" %command%` as a launch option, and also replaced  `start_protected_game.exe` with `armoredcore6.exe` to bypass anti-cheat.

_Could not figure out how to modify this command from Elden Ring `echo "%command%" | sed 's/start_protected_game/eldenring/' | WINEDLLOVERRIDES="dinput8.dll=n,b" sh`_

**Comment by Cloudef** [comment]
`echo "%command%" | sed 's/start_protected_game/armoredcore6/' | WINEDLLOVERRIDES="dinput8.dll=n,b" sh`
Should work as modified command. I may make elden-proton support ac6 as well at some point.

**Comment by hurrisonferd** [comment]
I don't know if this should be a separate thread, but im having some mod issues myself. I'm trying to do the armoury mod. My paths are similar to the ones above with the launch options set as well

**Comment by ArifXDD** [comment]
Do you mind make a tutorial video? I already follow everything that you listed.. the mod still won't show up except .Bin format mod, that one work

**Comment by ArifXDD** [comment]
Finally managed to make the mod working, I forgot to put the command line on lunch options. Thanks man
