### ISSUE TITLE
Issue on Steam Deck

### ISSUE THREAD

**Issue by NogardDrago** [Cloudef/ModEngine2#20]
First of all, thank you for the awesome works on this one.

One particular problem I faced when using this on steamdeck is that with this mod: https://www.nexusmods.com/eldenring/mods/4075?tab=posts&BH=7
The Parry animation and posture damage doesnt work, everything else still work. And when I install this on window it works perfectly. Any chance u can look into it a bit, or at least guess the general issues?
Thank you very much for your time.

**Comment by Cloudef** [comment]
Hello, can you try with https://github.com/Cloudef/elden-proton as well?

**Comment by NogardDrago** [comment]
Lemme try it and get back to you later ^^

**Comment by NogardDrago** [comment]
When I tried using your bash after setting the launch option it just return Required files failed to download. My internet is working fine

**Comment by Cloudef** [comment]
Sadly I don't have steam deck to test, but since it uses flatpak, could it be the same issue as here? 
Did you simply get "Required files failed to download", and no "Integrity check failed"?

Also maybe you can try running the script with `bash -x` from terminal (in desktop mode) and post the output.
(This won't run the game, but lets me see if some command is failing)

https://github.com/Cloudef/elden-proton/issues/4
I'll test the mod during weekend.

**Comment by NogardDrago** [comment]
Ty, Im at work right now so I will test it when I got home. Im not really familiar with the whole gaming on linux things, so I dont know what flatpak is, I just simply use ur bash. I will try the solution in that issue later

**Comment by Cloudef** [comment]
I fixed bunch of steam deck related issues on the elden proton repo so please try it again when you can.

**Comment by NogardDrago** [comment]
After trying again it worked! Also the mods working fine as intended now, tysm

**Comment by RickWang000** [comment]
> After trying again it worked! Also the mods working fine as intended now, tysm

Hello! I'd like to ask how you load mods through ModEngine2 after installing Elden Proton. Previously, I copied the two DLLs from ModEngine2 to the mods folder of Mod Loader, but like you, animations and posture damage don't work. However, when I launch the game with Elden Proton, there are no changes at all. If I delete the two DLLs from ModEngine2 in the mods folder, then ModEngine2 doesn't work at all. If I don't delete them, there's no difference from before. What should I do? Please share how you load ModEngine2 in Elden Proton. The relevant information is here: [my issue](https://github.com/Cloudef/elden-proton/issues/21). Thanks!
