### ISSUE TITLE
Minor suggestion for the installation process

### ISSUE THREAD

**Issue by hellwasta** [Cloudef/ModEngine2#4]
Hey could you do some change in the installation instruction to emphasise the need to create the modengine.toml as it is not so clear that it is required.
Could you also include the line below so people who don't use the randomizer mod do not end up overlooking this config and it would fit with other mods installation process.

mods = [
    { enabled = true, name = "default", path = "mod" }

If you feel generous maybe include a preconfig modengine.toml with the files.

Thank you.

**Comment by Cloudef** [comment]
Now it's recommended to use this for straigthforward setup https://github.com/Cloudef/elden-proton
