### ISSUE TITLE
Suggestion Please [guide]

### ISSUE THREAD

**Issue by Trexpool** [Cloudef/ModEngine2#5]
This might be asking a lot, but with so many people getting the steam deck and are unfamiliar with Linux, I think it will pay off in the future. 

Could someone provide a comprehensive guide for installing mods using ModEngine2 simultaneously with EldenModLoader via proton workaround? Kindly, with pictures and examples of the different mod file type locations? For example, I understand .dll files go in the “mods” folder that is downloaded with the EldenModLoader, but where do the regulation.bin’s go? Some Nexus pages say they go in the game.exe folder of which will replace the game’s regulation.bin. However, ModEngine2 says to put them in the “mod” folder that came with the ModEngine2 download. I also noticed in the example provided for item randomization mod that the regulation.bin is located in the Randomize folder.  
Lastly, I haven’t been able to get a single mod with CHR files to work. Actually, I don’t think I’ve been able to get any mods to work correctly yet. 

Sorry, I’m a noob at Linux. I just got a steam deck. Teehee. 🥲

**Comment by Trexpool** [comment]
UPDATE:

I got my mods to work!!! 

First tried Firebending and then Airbending (which is totally compatible with update 1.06) and then the whole movement set clevererraptor6. Works like a charm. 

Will post details soon.

**Comment by Trexpool** [comment]
Here's my steps:

- I used the launch option as illustrated on proton compatibility post. Set steam compatibility to proton experimental. 

- Installed the Mod Loader according to the instructions. 

- Dropped the Modengine2 folder in the "game" folder where eldenring.exe is located. 

- Duplicated the config_eldenring.toml file and renamed it to modengine.toml. 

- Took the ".dll" files from the Modengine2 "bin" folder and dropped them in the "mods" folder. 

- I did NOT change the game regulation.bin file. 

- Placed the modded .bin files in "mod" folder along with all the other modded files. 

That's it!!!

Run your game like normal!



(I saw once that someone could get multiple reg.bin files to run in the mod folder but I couldn't figure out how.)

**Comment by Trexpool** [comment]
![image](https://user-images.githubusercontent.com/62812047/191063423-ef4ef540-b602-4ccf-a5a0-34ba86e62973.jpeg)![image](https://user-images.githubusercontent.com/62812047/191063453-4a73cad2-5333-48c8-b118-cef738f63070.jpeg)![Uploading 191063470...]![Uploading 191063497...]![Uploading 191063500...]

**Comment by willyuewu** [comment]
You are amazing! Tried a couple solutions and yours do point out the important part, dropping the modenging2 folder (within the whole zip file, which contains the mod engine program) into the directory.
Just one minor correction, the dll files are in the bin folder rather than the lib folder.

**Comment by Trexpool** [comment]
> You are amazing! Tried a couple solutions and yours do point out the important part, dropping the modenging2 folder (within the whole zip file, which contains the mod engine program) into the directory.
> Just one minor correction, the dll files are in the bin folder rather than the lib folder.

Haha thank you for the kind words! I have updated my comment to show “bin” instead of lib.

I’m glad my explanation was helpful to someone at least!!

**Comment by Almotic** [comment]
Hey sorry for having to ask this but I am clueless on this. I followed your steps exactly and I think I got it working for the most part. Only issue I'm having is I have no idea how to get my mod that's just a CHR file to load into the game. Mod Loader only loads DLLs, but you mentioned trying to get CHR files to work in your first post. I am hoping you would let me know how to load them. Thank you.

**Comment by willyuewu** [comment]
> 

Hi, I think what you may want to try first is to make a CHR file mod work with modengine on a platform other than steam deck. (maybe this video is somewhat related? https://www.youtube.com/watch?v=85zsecbAaHE)

So I would guess you are trying to change the look of something. In this thread, what Trexpool shown in the picture is how to make mod engine work, than you can change the path of the toml file to the folder you place the mod in. Within the folder, the CHR files should still be placed in the chr folder. So the path should be like:
ELDEN RING
└── Game
|
├── mods
---- │ ├── lua.dll
----│ ├── modengine2.dll
├── modengine2
----│ ├──....
├── your_mod_name
----│ ├──chr
----│ ├──menu
----│ ├──parts
----| ├──...
├── movie
├── sd
├── dinput8.dll
├── mod_loader_config.ini
├── modengine.toml (point to the your_mod_name folder)
├── ...

**Comment by Almotic** [comment]
Thank you so much! I got the mod to work.
